/**
 * SOURCE-MANIFEST SCHEMA
 *
 * The shape of `tools/manifest/*.json` — the hand-curated, committed,
 * declarative description of every third-party asset the game pulls in.
 *
 * ── WHY THIS IS NOT `IAssetManifest` DIRECTLY ──────────────────────────────
 * `IAssetManifest` (src/types/assets.ts) is the BUILT artefact: it carries
 * `sha256` of the downloaded bytes and an `outputs[]` array of transcoded
 * files. Neither exists before the pipeline has run, so neither can be
 * hand-authored. The source manifest is the INPUT; `buildAssetManifest()` in
 * `manifest.ts` turns it into a conforming `IAssetManifest` once the fetch and
 * process stages have filled in the facts.
 *
 * Everything in the source manifest is either (a) hand-curated intent — ids,
 * tags, tier ladders, material specs — or (b) verifiable provenance pulled
 * from the provider API: exact per-file URL, md5 and byte count. Nothing here
 * is guessed.
 *
 * ── ONE ENTRY, MANY FILES ──────────────────────────────────────────────────
 * A PBR material is three JPEGs; a Poly Haven model is a .gltf plus a .bin
 * plus a handful of textures. `files[]` lists every one of them with its own
 * md5, so a corrupt or truncated download is caught per file rather than
 * per asset.
 *
 * TYPE-ONLY file — it erases completely.
 */

import type {
  AssetKind,
  ColorSpace,
  IAssetAttribution,
  MaterialSpec,
  QualityTier,
  TargetFormat,
  TextureCodec,
  TextureRole,
} from '@/types';

/* -------------------------------------------------------------------------- */
/* Providers                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Where an asset comes from.
 *
 *   'polyhaven'  — api.polyhaven.com. CC0, and the only source that publishes
 *                  a per-file md5, which is why it is the primary provider.
 *   'ambientcg'  — ambientcg.com. CC0 but ships whole-material zips with no
 *                  hashes; secondary source, used only where Poly Haven has a
 *                  genuine gap.
 *   'procedural' — generated by this repo's own pipeline. No download, no
 *                  files[]; the entry exists so consumers have a stable id.
 */
export type AssetProviderId = 'polyhaven' | 'ambientcg' | 'procedural';

/** Which Poly Haven index an id lives in. */
export type PolyHavenType = 'textures' | 'models' | 'hdris';

/* -------------------------------------------------------------------------- */
/* Source files                                                               */
/* -------------------------------------------------------------------------- */

/**
 * One downloadable file belonging to an entry, with the integrity data the
 * provider published for it.
 *
 * `path` is where the file is materialised under `assets/source/`. For glTF
 * assets it MUST preserve the relative layout the .gltf references
 * (`textures/foo_2k.jpg`), or the loader cannot resolve its own images.
 */
export interface ISourceFile {
  /**
   * Provider-side key. For Poly Haven textures this is the map name
   * (`Diffuse`, `nor_gl`, `arm`); for models it is the include-path
   * (`textures/x.jpg`, `x.bin`) or `gltf` for the root document.
   */
  readonly key: string;
  /** Semantic role, when the file is a texture. Drives the colour space. */
  readonly role?: TextureRole;
  /** Channel interpretation. Required whenever `role` is set. */
  readonly colorSpace?: ColorSpace;
  /** Destination path relative to `assets/source/`. */
  readonly path: string;
  /** Exact download URL, as published by the provider API. */
  readonly url: string;
  /** Provider-published md5 of the file. Verified after every download. */
  readonly md5: string;
  /** Provider-published size in bytes. Verified after every download. */
  readonly bytes: number;
  /** Provider resolution label, e.g. '4k'. */
  readonly resolution?: string;
  /** File extension without the dot: 'jpg' | 'png' | 'gltf' | 'bin' | 'hdr'. */
  readonly format: string;
  /** True for the file a loader is pointed at (the .gltf, the .hdr). */
  readonly root?: boolean;
}

/* -------------------------------------------------------------------------- */
/* Quality tiers                                                              */
/* -------------------------------------------------------------------------- */

/**
 * What one quality tier should be built to. Deliberately terse: the fields
 * that vary per asset live here, and everything mechanical (colour space,
 * normal-map mode, alpha) is derived per file from its `role` and `format`
 * by `compressionProfileFor()`. That keeps a 41-material manifest readable
 * instead of burying it under 369 near-identical profile objects.
 */
export interface ITierTarget {
  /** Longest-edge clamp in px for this tier's textures. */
  readonly maxDimension: number;
  /** GPU codec for this tier's textures. */
  readonly codec: TextureCodec;
  /** Encoder quality 0..100. */
  readonly quality: number;
  /** Zstandard supercompression of the KTX2 container. */
  readonly zstd?: boolean;
  /** Zstandard level 1..22. */
  readonly zstdLevel?: number;
  /** Fraction of source triangles retained, 0..1. Models only. */
  readonly simplifyRatio?: number;
  /** Draco geometry compression. Models only. */
  readonly draco?: boolean;
  /** meshoptimizer vertex-cache/overdraw pass. Models only. */
  readonly meshopt?: boolean;
  /** Position quantisation bits. Models only. */
  readonly positionBits?: number;
  /** Normal/UV quantisation bits. Models only. */
  readonly normalBits?: number;
}

export type TierTargets = Readonly<Partial<Record<QualityTier, ITierTarget>>>;

/* -------------------------------------------------------------------------- */
/* Entries                                                                    */
/* -------------------------------------------------------------------------- */

/** Fields every source entry carries, whatever its kind. */
export interface ISourceEntryBase {
  /** Stable, globally unique, dot-namespaced runtime key. */
  readonly id: string;
  readonly kind: AssetKind;
  /** Human-readable name, for the credits screen and tooling. */
  readonly name: string;
  readonly provider: AssetProviderId;
  /** The provider's own id, e.g. 'asphalt_02'. */
  readonly providerAssetId: string;
  /** Which provider index the id lives in. Poly Haven only. */
  readonly providerType?: PolyHavenType;
  /** Delivery format at runtime. */
  readonly targetFormat: TargetFormat;
  /** Provenance and licence. Never fabricated — pulled from `/info/<id>`. */
  readonly attribution: IAssetAttribution;
  /** Canonical asset page. Mirrors `attribution.sourceUrl`. */
  readonly sourceUrl: string;
  readonly tags: readonly string[];
  /** Load with the core bundle rather than on demand. */
  readonly preload?: boolean;
  /** Provider blurb, kept for tooling and search. */
  readonly description?: string;
  /** Curator's note — why this entry exists, or what is unusual about it. */
  readonly notes?: string;
  /** Per-tier build targets. Empty for procedural entries. */
  readonly tiers: TierTargets;
  /** Every file to download. Empty for procedural entries. */
  readonly files: readonly ISourceFile[];
}

/** A PBR material: a texture set plus the spec that binds it. */
export interface IMaterialSourceEntry extends ISourceEntryBase {
  readonly kind: 'material';
  readonly targetFormat: 'json';
  /** Declarative material description consumed by the material factory. */
  readonly spec: MaterialSpec;
  /** Texture ids this material binds, by role. Derived ids of the form
   *  `<materialId>.<role>` — the expansion in `buildAssetManifest()` creates
   *  a matching `ITextureAsset` for each. */
  readonly textureKeys: Readonly<Partial<Record<TextureRole, string>>>;
  /** Real-world size of one UV tile in metres. Drives correct tiling density. */
  readonly tileSizeMeters?: number;
  /** Provider's native pixel dimensions, as [w, h]. */
  readonly sourceResolution?: readonly [number | null, number | null];
}

/** A static mesh. */
export interface IModelSourceEntry extends ISourceEntryBase {
  readonly kind: 'model';
  readonly targetFormat: 'glb';
  /**
   * Provider-reported polycount of the source mesh. Treated as an estimate
   * only — `process-assets` overwrites `triangles` with the real count once
   * the glTF has actually been parsed.
   */
  readonly sourcePolycount?: number;
  /** Provider-reported bounding size [x, y, z] in metres. */
  readonly dimensionsMeters?: readonly number[];
  /** Many instances exist — enables GPU instancing. */
  readonly instanced?: boolean;
}

/** An environment map / sky. */
export interface IHDRISourceEntry extends ISourceEntryBase {
  readonly kind: 'hdri';
  readonly targetFormat: 'hdr' | 'exr' | 'ktx2';
  /** Equirectangular width in px of the source file. */
  readonly resolution: number;
  readonly timeOfDay?: 'dawn' | 'day' | 'dusk' | 'night';
  readonly hasIrradiance?: boolean;
}

export type AnySourceEntry = IMaterialSourceEntry | IModelSourceEntry | IHDRISourceEntry;

/* -------------------------------------------------------------------------- */
/* Manifest file                                                              */
/* -------------------------------------------------------------------------- */

/** One `tools/manifest/*.json` file. */
export interface ISourceManifest {
  /** Schema version. Bump on any breaking shape change. */
  readonly version: number;
  /** The single kind every entry in this file has. */
  readonly kind: 'material' | 'model' | 'hdri';
  /** Free text describing where the data came from. */
  readonly generator: string;
  /** Why these particular assets, and how they were chosen. */
  readonly description?: string;
  /** Provider resolution label the files were selected at. */
  readonly sourceResolution?: string;
  readonly entries: readonly AnySourceEntry[];
}

/* -------------------------------------------------------------------------- */
/* Cache and lockfile                                                         */
/* -------------------------------------------------------------------------- */

/** One row of `assets/source/index.json`, keyed by download URL. */
export interface ICacheRecord {
  readonly sha256: string;
  readonly md5: string;
  readonly bytes: number;
  /** ISO-8601 timestamp of the download that produced this blob. */
  readonly fetchedAt: string;
  /**
   * mtime of the CAS blob at the moment it was verified.
   *
   * This is the tripwire that makes cheap cache validation trustworthy: a
   * blob whose mtime has moved has been written to since it was checked, so
   * the next run re-hashes it instead of trusting its filename. Costs one
   * field and no extra I/O — the `stat` was already happening.
   */
  readonly mtimeMs?: number;
}

/** `assets/source/index.json` — the content-addressed store's url→blob map. */
export interface ICacheIndex {
  readonly version: number;
  readonly entries: Record<string, ICacheRecord>;
}

/** One row of `assets/assets.lock.json`, keyed by download URL. */
export interface ILockFileRecord {
  /** sha256 of the downloaded bytes. THE integrity anchor. */
  readonly sha256: string;
  /** Provider-published md5, re-verified on every fetch. */
  readonly md5: string;
  readonly bytes: number;
  /** Entry id this file belongs to. */
  readonly assetId: string;
  /** `ISourceFile.key`. */
  readonly key: string;
  /** Materialised path relative to `assets/source/`. */
  readonly path: string;
}

/** Per-entry rollup in the lockfile. */
export interface ILockAssetRecord {
  readonly provider: AssetProviderId;
  readonly providerAssetId: string;
  readonly kind: AssetKind;
  /**
   * Digest of the whole entry, NOT of any single file: sha256 over the
   * newline-joined, path-sorted list of `"<sha256>  <path>"` lines. Stable
   * across fetch order and machine, and changes if any member file changes.
   * This is what lands in `IAssetEntry.sha256`.
   */
  readonly digest: string;
  /** Sum of every member file's bytes. */
  readonly bytes: number;
  /** Member download URLs, sorted. */
  readonly files: readonly string[];
}

/** `assets/assets.lock.json` — committed; the reproducible-fetch contract. */
export interface IAssetLockFile {
  readonly version: number;
  readonly generatedAt: string;
  readonly generator: string;
  /** Every source file, keyed by URL. */
  readonly files: Record<string, ILockFileRecord>;
  /** Every entry, keyed by asset id. */
  readonly assets: Record<string, ILockAssetRecord>;
  readonly totals: {
    readonly entries: number;
    readonly files: number;
    readonly bytes: number;
  };
}

/* -------------------------------------------------------------------------- */
/* Fetch results                                                              */
/* -------------------------------------------------------------------------- */

/** What the fetcher learned about one file. */
export interface IFetchedFile {
  readonly file: ISourceFile;
  readonly sha256: string;
  readonly md5: string;
  readonly bytes: number;
  /** True when the blob was already in the CAS and nothing was transferred. */
  readonly cached: boolean;
  /** Bytes actually pulled over the wire (0 for a cache hit). */
  readonly transferred: number;
}

/** What the fetcher learned about one entry. */
export interface IFetchedEntry {
  readonly entry: AnySourceEntry;
  readonly files: readonly IFetchedFile[];
  readonly digest: string;
  readonly bytes: number;
}
