/**
 * ASSEMBLY — profile in, skinned geometry out
 *
 * This is the only file that knows the whole character. It resolves the LOD
 * table, builds every strand, drapes the costume, lofts the lot into one
 * buffer and derives morph targets.
 *
 * ── ONE MESH, NOT TWELVE ──────────────────────────────────────────────────
 * Everything merges into a SINGLE indexed geometry with a single skeleton.
 * Region colour rides in a vertex-colour attribute and material slots ride in
 * `geometry.groups`, so a caller who passes one material gets one draw call
 * per character (groups are ignored by three.js unless the material is an
 * array), and a caller who wants metal to look like metal can pass an array
 * and pay for it deliberately. On a mid-tier phone rendering a street full of
 * civilians, that choice is the difference between shipping and not.
 *
 * ── MORPH TARGETS COME FROM RE-LOFTING ────────────────────────────────────
 * A morph target is generated by rebuilding the character with a perturbed
 * profile and subtracting positions. Topology depends only on the LOD and the
 * costume — never on the profile's scalars — so the two builds are guaranteed
 * vertex-for-vertex compatible. That is far more robust than sculpting deltas,
 * and it means any parameter the generator understands can become a morph.
 */

import * as THREE from 'three';
import type { BodyProfile } from '@/types';
import { clamp01, lerp } from '@/util';
import type {
  GarmentSpec,
  HairSpec,
  HardSurfaceSpec,
  HumanoidStats,
  LodLevel,
  LodSettings,
  MeshRegionInfo,
  MorphSpec,
  Strand,
} from './types';
import { MeshSlot } from './types';
import { MeshBuilder, loftStrand } from './loft';
import { buildRig, type HumanoidRig } from './rig';
import { resolveShape, type ShapeOverrides, type ShapeParams } from './shape';
import {
  buildArmStrand,
  buildFootStrand,
  buildHandStrand,
  buildLegStrand,
  buildThumbStrand,
  buildTorsoStrand,
  type BodyContext,
  type Coat,
  type PaintFn,
} from './body';
import { buildEarStrand, buildNoseStrand } from './head';
import { buildCape, buildDress, buildSleeve, garmentAllowed } from './garment';
import { buildHair } from './hair';
import { buildHardSurface } from './hardsurface';
import { analyseTopology } from './analysis';

/* -------------------------------------------------------------------------- */
/* LOD table                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Radial resolution per tier.
 *
 * Section filtering (body.ts) handles resolution ALONG each strand; these
 * numbers handle resolution AROUND it. Sixteen segments on the torso is what
 * a bald head needs to stop faceting on the brow; ten on a limb is generous
 * because a limb is a near-circle; the crowd tier drops to hexagons and
 * pentagons, which at thirty metres are indistinguishable from cylinders.
 */
export const LOD_SETTINGS: Readonly<Record<LodLevel, LodSettings>> = {
  0: {
    level: 0,
    torsoSegments: 16,
    limbSegments: 10,
    detailSegments: 8,
    hands: true,
    feet: true,
    ears: true,
    nose: true,
    thumbs: true,
    garments: true,
    panels: true,
  },
  1: {
    level: 1,
    torsoSegments: 10,
    limbSegments: 7,
    detailSegments: 6,
    hands: true,
    feet: true,
    ears: false,
    nose: false,
    thumbs: false,
    garments: true,
    // At 12-32 m a 1.8 m character is ~60 px tall: armour plates and vent
    // grilles are sub-pixel. Colour still carries the mechanical read.
    panels: false,
  },
  2: {
    level: 2,
    torsoSegments: 6,
    limbSegments: 5,
    detailSegments: 4,
    hands: true,
    feet: true,
    ears: false,
    nose: false,
    thumbs: false,
    garments: true,
    panels: false,
  },
};

/**
 * Triangle ceilings the unit tests enforce, for a FULLY DRESSED character.
 *
 * The bare body is considerably cheaper — ~2.6k / ~1.06k / ~400 across the
 * ladder (asserted separately in the budget tests). Costume, sculpted hair and
 * hard-surface plates are what fill the remainder, and they are what a caller
 * trades away when a character has to be cheaper.
 */
export const LOD_BUDGET: Readonly<Record<LodLevel, number>> = { 0: 4000, 1: 1550, 2: 560 };

/** Ceilings for the naked body alone, with no costume, hair or plating. */
export const BODY_BUDGET: Readonly<Record<LodLevel, number>> = { 0: 2700, 1: 1200, 2: 450 };

/* -------------------------------------------------------------------------- */
/* Palette                                                                    */
/* -------------------------------------------------------------------------- */

/** Region colours baked into the vertex-colour attribute. */
export interface Palette {
  readonly skin: THREE.Color;
  readonly cloth: THREE.Color;
  readonly accent: THREE.Color;
  readonly hair: THREE.Color;
  readonly metal: THREE.Color;
  readonly vent: THREE.Color;
}

const DEFAULT_SKIN = 0xe8b48c;
const DEFAULT_CLOTH = 0x40587e;
const DEFAULT_ACCENT = 0x2a2d33;

/** Resolve a palette from the profile, with optional pins. */
export function resolvePalette(profile: BodyProfile, overrides?: Partial<Palette>): Palette {
  const base: Palette = {
    skin: new THREE.Color(profile.skinTone ?? DEFAULT_SKIN),
    cloth: new THREE.Color(profile.primaryColor ?? DEFAULT_CLOTH),
    accent: new THREE.Color(profile.secondaryColor ?? DEFAULT_ACCENT),
    hair: new THREE.Color(0x22190f),
    metal: new THREE.Color(0x9aa3ad),
    vent: new THREE.Color(0x14181d),
  };
  return overrides === undefined ? base : { ...base, ...overrides };
}

/* -------------------------------------------------------------------------- */
/* Costumes                                                                   */
/* -------------------------------------------------------------------------- */

/** Cloth thickness as a radial multiplier. */
const CLOTH_INFLATE = 1.035;
const TIGHT_INFLATE = 1.015;

/** Everyday clothes: shirt with short sleeves, trousers, shoes. */
export function casualCostume(palette: Palette): PaintFn {
  const shirt: Coat = { color: palette.cloth, inflate: CLOTH_INFLATE };
  const trousers: Coat = { color: palette.accent, inflate: CLOTH_INFLATE };
  const shoe: Coat = { color: palette.accent, inflate: TIGHT_INFLATE };
  const skin: Coat = { color: palette.skin };

  return (part, _key, at) => {
    switch (part) {
      case 'torso':
        if (at < 0.215) return trousers;
        if (at < 0.665) return shirt;
        return skin;
      case 'arm':
        return at < 0.5 ? shirt : skin;
      case 'leg':
        return at < 1.88 ? trousers : skin;
      case 'foot':
        return shoe;
      default:
        return skin;
    }
  };
}

/** A full-coverage bodysuit, the base for most hero costumes. */
export function bodysuitCostume(
  palette: Palette,
  options: {
    readonly gloveFrom?: number;
    readonly bootFrom?: number;
    readonly neckTo?: number;
  } = {}
): PaintFn {
  const suit: Coat = { color: palette.cloth, inflate: CLOTH_INFLATE };
  const trim: Coat = { color: palette.accent, inflate: TIGHT_INFLATE };
  const skin: Coat = { color: palette.skin };
  const gloveFrom = options.gloveFrom ?? 1.5;
  const bootFrom = options.bootFrom ?? 1.55;
  const neckTo = options.neckTo ?? 0.69;

  return (part, _key, at) => {
    switch (part) {
      case 'torso':
        return at < neckTo ? suit : skin;
      case 'arm':
        return at < gloveFrom ? suit : trim;
      case 'leg':
        return at < bootFrom ? suit : trim;
      case 'hand':
        return trim;
      case 'foot':
        return trim;
      default:
        return skin;
    }
  };
}

/* -------------------------------------------------------------------------- */
/* Build options and result                                                   */
/* -------------------------------------------------------------------------- */

export interface HumanoidOptions {
  readonly lod?: LodLevel;
  /** Pin resolved shape axes, for named characters. */
  readonly shape?: ShapeOverrides;
  readonly palette?: Partial<Palette>;
  /** Costume paint. Defaults to `casualCostume`. */
  readonly paint?: PaintFn;
  readonly garments?: GarmentSpec;
  readonly hair?: HairSpec;
  readonly hardSurface?: HardSurfaceSpec;
  /** Morph targets to derive by re-lofting. */
  readonly morphTargets?: readonly MorphSpec[];
}

export interface HumanoidBuild {
  readonly geometry: THREE.BufferGeometry;
  readonly rig: HumanoidRig;
  readonly regions: readonly MeshRegionInfo[];
  readonly stats: HumanoidStats;
  readonly profile: BodyProfile;
  readonly palette: Palette;
  readonly shape: ShapeParams;
  /** Morph target names, in `geometry.morphAttributes.position` order. */
  readonly morphNames: readonly string[];
}

/* -------------------------------------------------------------------------- */
/* Assembly                                                                   */
/* -------------------------------------------------------------------------- */

interface BodyStrands {
  readonly torso: Strand;
  readonly arms: Strand[];
  readonly legs: Strand[];
  readonly all: Strand[];
}

function buildBodyStrands(ctx: BodyContext): BodyStrands {
  const torso = buildTorsoStrand(ctx);
  const arms = [buildArmStrand(ctx, 'Left'), buildArmStrand(ctx, 'Right')];
  const legs = [buildLegStrand(ctx, 'Left'), buildLegStrand(ctx, 'Right')];
  const all: Strand[] = [torso, ...arms, ...legs];

  if (ctx.lod.hands) all.push(buildHandStrand(ctx, 'Left'), buildHandStrand(ctx, 'Right'));
  if (ctx.lod.thumbs) all.push(buildThumbStrand(ctx, 'Left'), buildThumbStrand(ctx, 'Right'));
  if (ctx.lod.feet) all.push(buildFootStrand(ctx, 'Left'), buildFootStrand(ctx, 'Right'));

  const earL = buildEarStrand(ctx, torso, 'Left');
  const earR = buildEarStrand(ctx, torso, 'Right');
  if (earL) all.push(earL);
  if (earR) all.push(earR);
  const nose = buildNoseStrand(ctx, torso, 0);
  if (nose) all.push(nose);

  return { torso, arms, legs, all };
}

function buildGarmentStrands(
  ctx: BodyContext,
  body: BodyStrands,
  spec: GarmentSpec,
  palette: Palette
): Strand[] {
  const d = ctx.rig.dims;
  const u = d.unit;
  const out: Strand[] = [];
  const cloth = spec.primary !== undefined ? new THREE.Color(spec.primary) : palette.cloth;
  const accent = spec.accent !== undefined ? new THREE.Color(spec.accent) : palette.accent;

  if (spec.collar === true && garmentAllowed(ctx.lod, 'trim')) {
    out.push(
      buildSleeve(ctx, {
        name: 'collar',
        source: body.torso,
        v0: 0.462,
        v1: 0.512,
        offset: 0.009 * u,
        offsetEnd: 0.006 * u,
        color: cloth,
        slot: MeshSlot.Cloth,
      })
    );
  }

  if (spec.belt === true && garmentAllowed(ctx.lod, 'trim')) {
    out.push(
      buildSleeve(ctx, {
        name: 'belt',
        source: body.torso,
        v0: 0.13,
        v1: 0.175,
        offset: 0.011 * u,
        color: accent,
      })
    );
  }

  if (spec.gloves === true && garmentAllowed(ctx.lod, 'trim')) {
    for (const arm of body.arms) {
      out.push(
        buildSleeve(ctx, {
          name: `${arm.name}Cuff`,
          source: arm,
          v0: 0.78,
          v1: 0.9,
          offset: 0.005 * u,
          offsetEnd: 0.003 * u,
          color: accent,
          flare: 1.18,
        })
      );
    }
  }

  if (spec.boots === true && garmentAllowed(ctx.lod, 'trim')) {
    for (const leg of body.legs) {
      out.push(
        buildSleeve(ctx, {
          name: `${leg.name}Boot`,
          source: leg,
          v0: 0.63,
          v1: 0.9,
          offset: 0.006 * u,
          offsetEnd: 0.004 * u,
          color: accent,
          flare: 1.14,
        })
      );
    }
  }

  if (spec.skirt === true && garmentAllowed(ctx.lod, 'silhouette')) {
    out.push(
      buildDress(ctx, {
        name: 'skirt',
        torso: body.torso,
        v0: 0.16,
        hemY: lerp(d.hipJointY, d.kneeY, 0.45),
        offset: 0.008 * u,
        flare: 1.22,
        color: cloth,
      })
    );
  }

  if (spec.coat === true && garmentAllowed(ctx.lod, 'silhouette')) {
    out.push(
      buildDress(ctx, {
        name: 'coat',
        torso: body.torso,
        v0: 0.34,
        hemY: lerp(d.hipJointY, d.kneeY, 0.6),
        offset: 0.012 * u,
        flare: 1.16,
        color: cloth,
      })
    );
  }

  return out;
}

/** Build one LOD of one character. */
export function buildHumanoid(profile: BodyProfile, options: HumanoidOptions = {}): HumanoidBuild {
  const lod = LOD_SETTINGS[options.lod ?? 0];
  const rig = buildRig(profile);
  const shape = resolveShape(profile, options.shape);
  const palette = resolvePalette(profile, options.palette);
  const paint = options.paint ?? casualCostume(palette);

  const ctx: BodyContext = { rig, shape, lod, paint, skinColor: palette.skin };
  const body = buildBodyStrands(ctx);
  const strands: Strand[] = [...body.all];

  const garments = options.garments;
  if (garments !== undefined && lod.garments) {
    strands.push(...buildGarmentStrands(ctx, body, garments, palette));
  }

  if (options.hair !== undefined) {
    strands.push(...buildHair(ctx, body.torso, options.hair));
  }

  if (options.hardSurface !== undefined) {
    strands.push(
      ...buildHardSurface(ctx, options.hardSurface, {
        arms: body.arms,
        legs: body.legs,
        torso: body.torso,
      })
    );
  }

  const builder = new MeshBuilder();
  for (const strand of strands) loftStrand(builder, strand);

  // The cape is not a swept ring set, so it emits directly into the builder.
  if (garments?.cape === true && garmentAllowed(lod, 'silhouette')) {
    const d = rig.dims;
    buildCape(ctx, builder, body.torso, {
      attachV: 0.452,
      hemY: lerp(d.hipsY, d.crotchY, 0.7),
      halfTop: 0.19,
      halfBottom: 0.36,
      flare: 1.68,
      thickness: 0.0045 * d.unit,
      color:
        garments.capeColor !== undefined ? new THREE.Color(garments.capeColor) : new THREE.Color(0xf2f0e8),
    });
  }

  const { geometry, regions } = builder.build();

  const morphNames: string[] = [];
  if (options.morphTargets !== undefined && options.morphTargets.length > 0) {
    applyMorphTargets(geometry, profile, options, morphNames);
  }

  const topology = analyseTopology(geometry);
  const box = geometry.boundingBox ?? new THREE.Box3();

  const stats: HumanoidStats = {
    lod: lod.level,
    vertices: geometry.getAttribute('position').count,
    triangles: (geometry.getIndex()?.count ?? 0) / 3,
    bones: rig.bones.length,
    components: topology.components,
    height: box.max.y - box.min.y,
  };

  return { geometry, rig, regions, stats, profile, palette, shape, morphNames };
}

/* -------------------------------------------------------------------------- */
/* Morph targets                                                              */
/* -------------------------------------------------------------------------- */

/** Perturb a profile by a morph spec's deltas. */
function perturb(profile: BodyProfile, spec: MorphSpec): BodyProfile {
  const d = spec.delta;
  return {
    ...profile,
    bulk: profile.bulk + (d.bulk ?? 0),
    shoulderWidth: profile.shoulderWidth + (d.shoulderWidth ?? 0),
    headScale: profile.headScale + (d.headScale ?? 0),
    limbLength: profile.limbLength + (d.limbLength ?? 0),
  };
}

function applyMorphTargets(
  geometry: THREE.BufferGeometry,
  profile: BodyProfile,
  options: HumanoidOptions,
  names: string[]
): void {
  const base = geometry.getAttribute('position');
  const targets: THREE.BufferAttribute[] = [];

  for (const spec of options.morphTargets ?? []) {
    const resolved = resolveShape(profile, options.shape);
    const shapeOverride: ShapeOverrides = {
      ...options.shape,
      ...(spec.delta.muscle !== undefined
        ? { muscle: clamp01(resolved.muscle + spec.delta.muscle) }
        : {}),
      ...(spec.delta.belly !== undefined
        ? { belly: clamp01(resolved.belly + spec.delta.belly) }
        : {}),
    };

    const variant = buildHumanoid(perturb(profile, spec), {
      ...options,
      shape: shapeOverride,
      morphTargets: undefined,
    });
    const other = variant.geometry.getAttribute('position');
    if (other.count !== base.count) {
      variant.geometry.dispose();
      throw new Error(
        `morph "${spec.name}": topology changed (${other.count} vs ${base.count} vertices)`
      );
    }

    const delta = new Float32Array(base.count * 3);
    for (let i = 0; i < base.count * 3; i++) {
      delta[i] = (other.array as ArrayLike<number>)[i]! - (base.array as ArrayLike<number>)[i]!;
    }
    const attribute = new THREE.Float32BufferAttribute(delta, 3);
    // three.js builds `morphTargetDictionary` from these names when the mesh
    // is constructed, so setting it here is what makes
    // `mesh.morphTargetInfluences[mesh.morphTargetDictionary.belly]` work.
    attribute.name = spec.name;
    targets.push(attribute);
    names.push(spec.name);
    variant.geometry.dispose();
  }

  if (targets.length > 0) {
    geometry.morphAttributes.position = targets;
    geometry.morphTargetsRelative = true;
  }
}

/** The variation morphs a crowd character ships with by default. */
export const CROWD_MORPHS: readonly MorphSpec[] = [
  { name: 'belly', delta: { belly: 0.55, bulk: 0.12 } },
  { name: 'broad', delta: { shoulderWidth: 0.18, muscle: 0.3 } },
  { name: 'slim', delta: { bulk: -0.22, belly: -0.3 } },
  { name: 'bigHead', delta: { headScale: 0.22 } },
];

/** Build all three LODs of one character from one description. */
export function buildHumanoidLODs(
  profile: BodyProfile,
  options: HumanoidOptions = {}
): [HumanoidBuild, HumanoidBuild, HumanoidBuild] {
  return [
    buildHumanoid(profile, { ...options, lod: 0 }),
    buildHumanoid(profile, { ...options, lod: 1, morphTargets: undefined }),
    buildHumanoid(profile, { ...options, lod: 2, morphTargets: undefined }),
  ];
}

/** Screen-space distance bands the LOD selector uses, in metres. */
export const LOD_DISTANCES: readonly number[] = [0, 12, 32];

/** Pick a LOD for a viewing distance. */
export function lodForDistance(metres: number): LodLevel {
  if (metres < LOD_DISTANCES[1]!) return 0;
  if (metres < LOD_DISTANCES[2]!) return 1;
  return 2;
}
