/**
 * LOFTING CORE
 *
 * Turns ordered cross-sections into skinned, UV'd, watertight triangles, and
 * evaluates the analytic skin weights that make the whole approach worthwhile.
 *
 * Three properties are load-bearing and every change here must preserve them:
 *
 *  1. WINDING. Ring parameter t always advances the same way relative to the
 *     sweep direction, and the ring frame always satisfies
 *     `cross(axisA, axisB) === axis`. Together those make the quad ordering
 *     `(i,k) (i,k+1) (i+1,k+1)` face outward for EVERY strand, however it is
 *     oriented. Tests assert positive signed volume per component, which is
 *     exactly a winding check.
 *
 *  2. WATERTIGHTNESS. The seam column is duplicated so u can reach 1.0, and
 *     flat caps duplicate their rim so the crease is hard. Duplicated
 *     vertices are bit-identical in position, so the surface is closed even
 *     though the index buffer is not welded. Manifold tests weld by position
 *     first — that is the correct way to test a UV-seamed mesh.
 *
 *  3. NORMALS. Averaged across position-welded vertices that share a smoothing
 *     group, so the UV seam does not show as a lighting crack, while flat caps
 *     and hard-surface panels keep genuine hard edges.
 */

import * as THREE from 'three';
import type { BoneName } from '@/types';
import { TAU, clamp01, smootherstep } from '@/util';
import type {
  MeshRegionInfo,
  MeshSlot,
  Ring,
  RingShape,
  SkinChain,
  SkinWeight4,
  Strand,
  UVRect,
} from './types';
import { packUV } from './uv';

/* -------------------------------------------------------------------------- */
/* Cross-section evaluation                                                   */
/* -------------------------------------------------------------------------- */

/** Signed power: keeps the superellipse symmetric through the origin. */
function signPow(value: number, power: number): number {
  const a = Math.abs(value);
  const r = power === 1 ? a : Math.pow(a, power);
  return value < 0 ? -r : r;
}

/**
 * Evaluate a cross-section at ring parameter `t` in 0..1.
 *
 * t=0 is -axisB (the BACK of an upright body), t=0.25 is +axisA, t=0.5 is
 * +axisB (the FRONT), t=0.75 is -axisA. Keeping the seam at the back is what
 * puts the face in the middle of its atlas rectangle.
 */
export function evalRingPoint(shape: RingShape, t: number, out: THREE.Vector2): THREE.Vector2 {
  const angle = TAU * t - Math.PI / 2;
  const ca = Math.cos(angle);
  const sa = Math.sin(angle);
  const exponent = shape.exponent ?? 2;
  const power = 2 / exponent;

  let a = shape.radiusA * signPow(ca, power);
  let b = shape.radiusB * signPow(sa, power);

  if (b >= 0) {
    if (shape.frontScale !== undefined) b *= shape.frontScale;
  } else if (shape.backScale !== undefined) {
    b *= shape.backScale;
  }

  a += shape.offsetA ?? 0;
  b += shape.offsetB ?? 0;

  return out.set(a, b);
}

/* -------------------------------------------------------------------------- */
/* Analytic skinning                                                          */
/* -------------------------------------------------------------------------- */

/** Ramp from 0 to 1 across [edge - width, edge + width]. */
function ramp(s: number, edge: number, width: number): number {
  if (width <= 0) return s < edge ? 0 : 1;
  return smootherstep(edge - width, edge + width, s);
}

const EMPTY_SKIN: SkinWeight4 = { index: [0, 0, 0, 0], weight: [1, 0, 0, 0] };

/**
 * Collapse an arbitrary bone->weight map into exactly four normalised slots.
 *
 * Ordering is weight-descending with a bone-index tiebreak, so the same
 * anatomical position always produces the same slot layout — which is what
 * lets morph targets be generated by re-lofting a perturbed profile.
 */
export function packSkin(
  contributions: ReadonlyMap<number, number>,
  fallbackBone = 0
): SkinWeight4 {
  const entries: [number, number][] = [];
  for (const [bone, weight] of contributions) {
    if (weight > 1e-5) entries.push([bone, weight]);
  }
  if (entries.length === 0) {
    return { index: [fallbackBone, fallbackBone, fallbackBone, fallbackBone], weight: [1, 0, 0, 0] };
  }

  entries.sort((x, y) => (y[1] === x[1] ? x[0] - y[0] : y[1] - x[1]));
  const kept = entries.slice(0, 4);

  let total = 0;
  for (const [, w] of kept) total += w;

  const index: [number, number, number, number] = [
    kept[0]![0],
    kept[0]![0],
    kept[0]![0],
    kept[0]![0],
  ];
  const weight: [number, number, number, number] = [0, 0, 0, 0];
  for (let i = 0; i < kept.length; i++) {
    index[i] = kept[i]![0];
    weight[i] = kept[i]![1] / total;
  }

  // Kill residual float error on the dominant slot so the sum is exactly 1.
  const sum = weight[0] + weight[1] + weight[2] + weight[3];
  weight[0] += 1 - sum;

  return { index, weight };
}

/**
 * Evaluate a bone chain at parameter `s`.
 *
 * Each span owns the surface between its own start and end, crossfading with
 * its neighbour over a window centred on the shared joint. Because the two
 * ramps at a joint are exact complements, the pair already sums to 1 before
 * normalisation — normalisation only ever has to correct overlapping windows
 * on very short bones.
 */
export function evaluateChain(
  chain: SkinChain,
  s: number,
  boneIndex: Readonly<Record<BoneName, number>>
): SkinWeight4 {
  const spans = chain.spans;
  if (spans.length === 0) return EMPTY_SKIN;

  const contributions = new Map<number, number>();

  for (let i = 0; i < spans.length; i++) {
    const span = spans[i]!;
    const prev = i > 0 ? spans[i - 1] : undefined;

    const enter = prev === undefined ? 1 : ramp(s, span.start, prev.blend ?? 0);
    const leave = i === spans.length - 1 ? 1 : 1 - ramp(s, span.end, span.blend ?? 0);
    const membership = enter * leave;
    if (membership <= 1e-5) continue;

    const idx = boneIndex[span.bone];
    contributions.set(idx, (contributions.get(idx) ?? 0) + membership);
  }

  if (chain.bias !== undefined) {
    for (const bias of chain.bias) {
      const falloff = 1 - clamp01(Math.abs(s - bias.at) / Math.max(bias.range, 1e-6));
      const amount = bias.amount * smootherstep(0, 1, falloff);
      if (amount <= 1e-5) continue;
      const idx = boneIndex[bias.bone];
      contributions.set(idx, (contributions.get(idx) ?? 0) + amount);
    }
  }

  const fallback = boneIndex[spans[0]!.bone];
  return packSkin(contributions, fallback);
}

/** Linearly blend two influence sets and renormalise to four slots. */
export function blendSkin(a: SkinWeight4, b: SkinWeight4, t: number): SkinWeight4 {
  const contributions = new Map<number, number>();
  const add = (skin: SkinWeight4, scale: number): void => {
    for (let i = 0; i < 4; i++) {
      const w = skin.weight[i]! * scale;
      if (w <= 0) continue;
      const idx = skin.index[i]!;
      contributions.set(idx, (contributions.get(idx) ?? 0) + w);
    }
  };
  add(a, 1 - t);
  add(b, t);
  return packSkin(contributions, a.index[0]!);
}

/** A single bone at full weight. */
export function rigidSkin(bone: BoneName, boneIndex: Readonly<Record<BoneName, number>>): SkinWeight4 {
  const i = boneIndex[bone];
  return { index: [i, i, i, i], weight: [1, 0, 0, 0] };
}

/* -------------------------------------------------------------------------- */
/* Mesh accumulation                                                          */
/* -------------------------------------------------------------------------- */

/** Quantisation used when welding positions for normals and manifold checks. */
const WELD_SCALE = 1e5;

/**
 * Append-only vertex/index accumulator.
 *
 * Plain number arrays rather than typed arrays: generation happens once at
 * load time and the counts are not known up front, so growth cost beats the
 * bookkeeping of resizing typed buffers.
 */
export class MeshBuilder {
  private readonly position: number[] = [];
  private readonly uv: number[] = [];
  private readonly color: number[] = [];
  private readonly skinIndex: number[] = [];
  private readonly skinWeight: number[] = [];
  private readonly smooth: number[] = [];
  private readonly index: number[] = [];
  private readonly regions: MeshRegionInfo[] = [];
  private open: { name: string; slot: MeshSlot; start: number } | undefined;

  get vertexCount(): number {
    return this.position.length / 3;
  }

  get triangleCount(): number {
    return this.index.length / 3;
  }

  beginRegion(name: string, slot: MeshSlot): void {
    if (this.open !== undefined) this.endRegion();
    this.open = { name, slot, start: this.index.length };
  }

  endRegion(): void {
    const open = this.open;
    if (open === undefined) return;
    const count = this.index.length - open.start;
    this.open = undefined;
    if (count === 0) return;
    this.regions.push({
      name: open.name,
      slot: open.slot,
      indexStart: open.start,
      indexCount: count,
      triangles: count / 3,
    });
  }

  addVertex(
    p: THREE.Vector3,
    u: number,
    v: number,
    color: THREE.Color,
    skin: SkinWeight4,
    smoothGroup: number
  ): number {
    const id = this.position.length / 3;
    this.position.push(p.x, p.y, p.z);
    this.uv.push(u, v);
    this.color.push(color.r, color.g, color.b);
    this.skinIndex.push(skin.index[0], skin.index[1], skin.index[2], skin.index[3]);
    this.skinWeight.push(skin.weight[0], skin.weight[1], skin.weight[2], skin.weight[3]);
    this.smooth.push(smoothGroup);
    return id;
  }

  addTriangle(a: number, b: number, c: number): void {
    this.index.push(a, b, c);
  }

  /** Two triangles across a quad, wound so `a -> b -> c -> d` faces outward. */
  addQuad(a: number, b: number, c: number, d: number): void {
    this.index.push(a, b, c, a, c, d);
  }

  /**
   * Smooth normals, welded by (quantised position, smoothing group).
   *
   * Face normals are accumulated unnormalised so they carry triangle area as
   * their magnitude; that weights large faces more than slivers and is what
   * keeps the shoulder from developing a lighting pinch where a dense ring
   * meets a sparse one.
   */
  private computeNormals(): Float32Array {
    const count = this.vertexCount;
    const normals = new Float32Array(count * 3);
    const groups = new Map<string, number[]>();

    for (let i = 0; i < count; i++) {
      const key =
        `${Math.round(this.position[i * 3]! * WELD_SCALE)}|` +
        `${Math.round(this.position[i * 3 + 1]! * WELD_SCALE)}|` +
        `${Math.round(this.position[i * 3 + 2]! * WELD_SCALE)}|${this.smooth[i]}`;
      const bucket = groups.get(key);
      if (bucket === undefined) groups.set(key, [i]);
      else bucket.push(i);
    }

    const accum = new Map<string, THREE.Vector3>();
    const owner = new Array<string>(count);
    for (const [key, members] of groups) {
      accum.set(key, new THREE.Vector3());
      for (const m of members) owner[m] = key;
    }

    const pa = new THREE.Vector3();
    const pb = new THREE.Vector3();
    const pc = new THREE.Vector3();
    const ab = new THREE.Vector3();
    const cb = new THREE.Vector3();
    const faceNormal = new THREE.Vector3();

    for (let t = 0; t < this.index.length; t += 3) {
      const ia = this.index[t]!;
      const ib = this.index[t + 1]!;
      const ic = this.index[t + 2]!;
      pa.fromArray(this.position, ia * 3);
      pb.fromArray(this.position, ib * 3);
      pc.fromArray(this.position, ic * 3);
      cb.subVectors(pc, pb);
      ab.subVectors(pa, pb);
      faceNormal.crossVectors(cb, ab);
      accum.get(owner[ia]!)!.add(faceNormal);
      accum.get(owner[ib]!)!.add(faceNormal);
      accum.get(owner[ic]!)!.add(faceNormal);
    }

    const n = new THREE.Vector3();
    for (let i = 0; i < count; i++) {
      n.copy(accum.get(owner[i]!)!);
      if (n.lengthSq() < 1e-20) n.set(0, 1, 0);
      else n.normalize();
      normals[i * 3] = n.x;
      normals[i * 3 + 1] = n.y;
      normals[i * 3 + 2] = n.z;
    }
    return normals;
  }

  /** Finalise into a skinning-ready `BufferGeometry`. */
  build(): { geometry: THREE.BufferGeometry; regions: readonly MeshRegionInfo[] } {
    this.endRegion();

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.Float32BufferAttribute(this.position, 3));
    geometry.setAttribute('normal', new THREE.BufferAttribute(this.computeNormals(), 3));
    geometry.setAttribute('uv', new THREE.Float32BufferAttribute(this.uv, 2));
    geometry.setAttribute('color', new THREE.Float32BufferAttribute(this.color, 3));
    geometry.setAttribute('skinIndex', new THREE.Uint16BufferAttribute(this.skinIndex, 4));
    geometry.setAttribute('skinWeight', new THREE.Float32BufferAttribute(this.skinWeight, 4));
    geometry.setIndex(this.index);

    // Merge adjacent regions that share a slot: three.js issues one draw call
    // per group, and a character has far more regions than materials.
    let cursor = -1;
    for (const region of this.regions) {
      const groups = geometry.groups;
      const last = cursor >= 0 ? groups[cursor] : undefined;
      if (last !== undefined && last.materialIndex === region.slot) {
        last.count += region.indexCount;
      } else {
        geometry.addGroup(region.indexStart, region.indexCount, region.slot);
        cursor = geometry.groups.length - 1;
      }
    }

    geometry.computeBoundingBox();
    geometry.computeBoundingSphere();
    return { geometry, regions: this.regions };
  }
}

/* -------------------------------------------------------------------------- */
/* Strand lofting                                                             */
/* -------------------------------------------------------------------------- */

/** Sweep directions, one per ring: explicit, else a central difference. */
function ringAxes(rings: readonly Ring[]): THREE.Vector3[] {
  const out: THREE.Vector3[] = [];
  for (let i = 0; i < rings.length; i++) {
    const ring = rings[i]!;
    if (ring.axis !== undefined) {
      out.push(ring.axis.clone().normalize());
      continue;
    }
    const prev = rings[Math.max(0, i - 1)]!;
    const next = rings[Math.min(rings.length - 1, i + 1)]!;
    const axis = next.center.clone().sub(prev.center);
    if (axis.lengthSq() < 1e-12) axis.set(0, 1, 0);
    out.push(axis.normalize());
  }
  return out;
}

/**
 * Rotation-minimising frames along the sweep.
 *
 * Naively rebuilding the frame from a fixed up-vector makes the mesh spin
 * where the spline turns (visible as texture swirl and as twisted rings in the
 * ankle and cape). Parallel transport carries the previous frame through the
 * minimal rotation between consecutive tangents instead, so the surface only
 * twists where the geometry genuinely does.
 */
function ringFrames(
  axes: readonly THREE.Vector3[],
  hint: THREE.Vector3
): { a: THREE.Vector3; b: THREE.Vector3 }[] {
  const frames: { a: THREE.Vector3; b: THREE.Vector3 }[] = [];
  const q = new THREE.Quaternion();

  let a = hint.clone();
  a.addScaledVector(axes[0]!, -a.dot(axes[0]!));
  if (a.lengthSq() < 1e-10) {
    a = Math.abs(axes[0]!.y) < 0.9 ? new THREE.Vector3(0, 1, 0) : new THREE.Vector3(1, 0, 0);
    a.addScaledVector(axes[0]!, -a.dot(axes[0]!));
  }
  a.normalize();

  for (let i = 0; i < axes.length; i++) {
    if (i > 0) {
      q.setFromUnitVectors(axes[i - 1]!, axes[i]!);
      a = a.clone().applyQuaternion(q);
      a.addScaledVector(axes[i]!, -a.dot(axes[i]!));
      if (a.lengthSq() < 1e-10) a.set(axes[i]!.y, axes[i]!.z, axes[i]!.x);
      a.normalize();
    }
    frames.push({ a: a.clone(), b: new THREE.Vector3().crossVectors(axes[i]!, a) });
  }
  return frames;
}

const _p = new THREE.Vector3();
const _local = new THREE.Vector2();
const _uv: [number, number] = [0, 0];
const _axisA = new THREE.Vector3();
const _axisB = new THREE.Vector3();

/**
 * Height of a pole cap over a cross-section.
 *
 * The SMALLER semi-axis, not the mean: capping an ellipse at its mean radius
 * produces a cone on the narrow axis and a dent on the wide one. Bounding the
 * dome by the minor axis is the only choice that stays plausible for both a
 * near-circular limb end and a flat paddle like a fingertip.
 */
export function poleHeight(shape: RingShape): number {
  return Math.min(Math.abs(shape.radiusA), Math.abs(shape.radiusB)) * 0.92;
}

/**
 * Triangulate one strand into the builder.
 *
 * Returns the per-ring vertex id table so callers (garment shells, panels,
 * decals) can attach to exact surface positions rather than guessing.
 */
export function loftStrand(builder: MeshBuilder, strand: Strand): number[][] {
  const { rings, radialSegments: segments, uvRect } = strand;
  if (rings.length < 2) return [];

  const axes = ringAxes(rings);
  const frames = ringFrames(axes, strand.frameHint);
  const grid: number[][] = [];

  builder.beginRegion(strand.name, strand.slot);

  for (let i = 0; i < rings.length; i++) {
    const ring = rings[i]!;
    const frame = frames[i]!;
    _axisA.copy(frame.a);
    _axisB.copy(frame.b);
    if (ring.roll !== undefined && ring.roll !== 0) {
      _axisA.applyAxisAngle(axes[i]!, ring.roll);
      _axisB.applyAxisAngle(axes[i]!, ring.roll);
    }
    const color = ring.color ?? strand.color;

    const row: number[] = [];
    // segments + 1 columns: the last duplicates the first so u can reach 1.
    for (let k = 0; k <= segments; k++) {
      const t = k / segments;
      evalRingPoint(ring.shape, t === 1 ? 0 : t, _local);
      _p.copy(ring.center).addScaledVector(_axisA, _local.x).addScaledVector(_axisB, _local.y);
      packUV(uvRect, t, ring.v, _uv);
      row.push(builder.addVertex(_p, _uv[0], _uv[1], color, ring.skin, strand.smoothGroup));
    }
    grid.push(row);
  }

  for (let i = 0; i < rings.length - 1; i++) {
    const lo = grid[i]!;
    const hi = grid[i + 1]!;
    for (let k = 0; k < segments; k++) {
      builder.addQuad(lo[k]!, lo[k + 1]!, hi[k + 1]!, hi[k]!);
    }
  }

  capStrand(builder, strand, grid, axes, frames, true);
  capStrand(builder, strand, grid, axes, frames, false);

  builder.endRegion();
  return grid;
}

function capStrand(
  builder: MeshBuilder,
  strand: Strand,
  grid: readonly number[][],
  axes: readonly THREE.Vector3[],
  frames: readonly { a: THREE.Vector3; b: THREE.Vector3 }[],
  atStart: boolean
): void {
  const mode = atStart ? strand.capStart : strand.capEnd;
  if (mode === 'none') return;

  const i = atStart ? 0 : grid.length - 1;
  const ring = strand.rings[i]!;
  const row = grid[i]!;
  const segments = strand.radialSegments;
  const axis = axes[i]!;
  const outward = atStart ? -1 : 1;

  if (mode === 'pole') {
    // Reuse the rim vertices so the dome stays smooth-shaded, and push the
    // pole out by roughly the rim radius so the end reads as a hemisphere
    // rather than a cone.
    const explicit = atStart ? strand.poleStart : strand.poleEnd;
    _p.copy(ring.center).addScaledVector(axis, outward * (explicit ?? poleHeight(ring.shape)));
    packUV(strand.uvRect, 0.5, atStart ? Math.max(0, ring.v - 0.03) : Math.min(1, ring.v + 0.03), _uv);
    const pole = builder.addVertex(
      _p,
      _uv[0],
      _uv[1],
      ring.color ?? strand.color,
      ring.skin,
      strand.smoothGroup
    );
    for (let k = 0; k < segments; k++) {
      if (atStart) builder.addTriangle(row[k + 1]!, row[k]!, pole);
      else builder.addTriangle(row[k]!, row[k + 1]!, pole);
    }
    return;
  }

  // Flat cap: duplicate the rim into its own smoothing group so the silhouette
  // edge stays sharp, then fan to a centre vertex.
  const group = strand.smoothGroup + 0x4000 + (atStart ? 0 : 1);
  const frame = frames[i]!;
  const rim: number[] = [];
  for (let k = 0; k <= segments; k++) {
    const t = k / segments;
    evalRingPoint(ring.shape, t === 1 ? 0 : t, _local);
    _p.copy(ring.center).addScaledVector(frame.a, _local.x).addScaledVector(frame.b, _local.y);
    packUV(strand.uvRect, t, ring.v, _uv);
    rim.push(
      builder.addVertex(_p, _uv[0], _uv[1], ring.color ?? strand.color, ring.skin, group)
    );
  }
  _p.copy(ring.center);
  packUV(strand.uvRect, 0.5, ring.v, _uv);
  const hub = builder.addVertex(
    _p,
    _uv[0],
    _uv[1],
    ring.color ?? strand.color,
    ring.skin,
    group
  );
  for (let k = 0; k < segments; k++) {
    if (atStart) builder.addTriangle(rim[k + 1]!, rim[k]!, hub);
    else builder.addTriangle(rim[k]!, rim[k + 1]!, hub);
  }
}

/** Convenience: build a `Strand` with the fields most call sites share. */
export function makeStrand(
  name: string,
  rings: readonly Ring[],
  options: {
    readonly radialSegments: number;
    readonly uvRect: UVRect;
    readonly slot: MeshSlot;
    readonly color: THREE.Color;
    readonly frameHint: THREE.Vector3;
    readonly smoothGroup: number;
    readonly capStart?: import('./types').CapMode;
    readonly capEnd?: import('./types').CapMode;
    readonly poleStart?: number;
    readonly poleEnd?: number;
  }
): Strand {
  return {
    name,
    rings,
    radialSegments: options.radialSegments,
    capStart: options.capStart ?? 'pole',
    capEnd: options.capEnd ?? 'pole',
    uvRect: options.uvRect,
    slot: options.slot,
    color: options.color,
    frameHint: options.frameHint,
    smoothGroup: options.smoothGroup,
    poleStart: options.poleStart,
    poleEnd: options.poleEnd,
  };
}
