/**
 * MANIFEST PARSING
 *
 * `assets.runtime.json` is a superset of `IAssetManifest`: the texture
 * pipeline appends `tiersBuilt`, `pipeline` and `environments` blocks that the
 * type contract does not model. Rather than cast the whole file and hope, this
 * module reads the extensions structurally and hands back both views — the
 * typed manifest for `IAssetRegistry.manifest`, and the extension blocks for
 * the consumers that need them.
 *
 * `environments[].meanLuminance` is the one nobody may drop. The four HDRIs
 * are NOT exposure-matched: their peak luminances span five orders of
 * magnitude (4.0 to 137 000) while their means sit within 1.5x of each other.
 * The sky system divides by the mean to put them on a common scale. Swallowing
 * the field here would silently reintroduce a midnight as bright as noon, so
 * it is surfaced verbatim on `IRuntimeManifest.environments`.
 */

import type { AnyAssetEntry, IAssetManifest, QualityTier } from '@/types';
import { TIER_ORDER } from './constants';

/* -------------------------------------------------------------------------- */
/* Extension blocks                                                           */
/* -------------------------------------------------------------------------- */

/** Per-environment measurements the HDRI pipeline exports. */
export interface IEnvironmentRecord {
  /** 27 floats: 9 SH bands x RGB, interleaved. THREE.SphericalHarmonics3 order. */
  readonly sh9?: readonly number[];
  /** Sidecar holding the same coefficients, for consumers without the manifest. */
  readonly shFile?: string;
  /** Area-weighted mean luminance of the SOURCE HDRI. Normalise by this. */
  readonly meanLuminance?: number;
  /** Peak luminance of the source, before half-float conversion. */
  readonly maxLuminance?: number;
}

/** Provenance block describing how the binaries were encoded. */
export interface IPipelineRecord {
  readonly toolVersion?: string;
  readonly encoder?: string;
  /** 'bottom-left' for this pipeline: flipY is baked into the bytes. */
  readonly textureOrigin?: string;
  readonly flipY?: boolean;
  readonly notes?: readonly string[];
}

/** The manifest as actually served, extensions included. */
export interface IRuntimeManifest extends IAssetManifest {
  /** Tiers the pipeline BUILT. Not a promise that they were PACKAGED. */
  readonly tiersBuilt: readonly QualityTier[];
  readonly pipeline?: IPipelineRecord;
  readonly environments: Readonly<Record<string, IEnvironmentRecord>>;
}

/* -------------------------------------------------------------------------- */
/* Parsing                                                                    */
/* -------------------------------------------------------------------------- */

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function readTiers(value: unknown): readonly QualityTier[] {
  if (!Array.isArray(value)) return [];
  return value.filter((tier): tier is QualityTier =>
    TIER_ORDER.includes(tier as QualityTier)
  );
}

function readEnvironments(value: unknown): Record<string, IEnvironmentRecord> {
  const out: Record<string, IEnvironmentRecord> = {};
  if (!isRecord(value)) return out;
  for (const [id, raw] of Object.entries(value)) {
    if (!isRecord(raw)) continue;
    const sh9 = Array.isArray(raw.sh9) && raw.sh9.length === 27 ? (raw.sh9 as number[]) : undefined;
    out[id] = {
      sh9,
      shFile: typeof raw.shFile === 'string' ? raw.shFile : undefined,
      meanLuminance:
        typeof raw.meanLuminance === 'number' && raw.meanLuminance > 0
          ? raw.meanLuminance
          : undefined,
      maxLuminance: typeof raw.maxLuminance === 'number' ? raw.maxLuminance : undefined,
    };
  }
  return out;
}

/**
 * Validate and normalise a parsed `assets.runtime.json`.
 *
 * Defensive on purpose: this file is generated by a different workstream and
 * shipped inside an APK, so a shape change must degrade rather than throw
 * halfway through the boot screen. Anything unreadable becomes an empty
 * collection, and the caller sees an empty manifest instead of an exception.
 */
export function parseRuntimeManifest(raw: unknown): IRuntimeManifest {
  const source = isRecord(raw) ? raw : {};
  const entries = Array.isArray(source.entries)
    ? source.entries.filter(
        (entry): entry is AnyAssetEntry =>
          isRecord(entry) && typeof entry.id === 'string' && typeof entry.kind === 'string'
      )
    : [];

  // A manifest that names no tiers is treated as mobile-only, which is the
  // safe direction: the runtime under-fetches rather than 404s.
  const declared = readTiers(source.tiersBuilt);
  const fromOutputs = new Set<QualityTier>();
  for (const entry of entries) {
    for (const output of entry.outputs ?? []) {
      if (TIER_ORDER.includes(output.tier)) fromOutputs.add(output.tier);
    }
  }
  const tiersBuilt = declared.length > 0 ? declared : [...fromOutputs];

  return {
    version: typeof source.version === 'number' ? source.version : 0,
    generatedAt: typeof source.generatedAt === 'string' ? source.generatedAt : '',
    generator: typeof source.generator === 'string' ? source.generator : 'unknown',
    generatedRoot: typeof source.generatedRoot === 'string' ? source.generatedRoot : undefined,
    entries,
    totalBytes: isRecord(source.totalBytes)
      ? (source.totalBytes as Partial<Record<QualityTier, number>>)
      : undefined,
    tiersBuilt: tiersBuilt.length > 0 ? tiersBuilt : ['mobile'],
    pipeline: isRecord(source.pipeline) ? (source.pipeline as IPipelineRecord) : undefined,
    environments: readEnvironments(source.environments),
  };
}

/** An empty manifest, used when the index cannot be fetched at all. */
export function emptyRuntimeManifest(): IRuntimeManifest {
  return {
    version: 0,
    generatedAt: '',
    generator: 'none',
    entries: [],
    tiersBuilt: ['mobile'],
    environments: {},
  };
}

/* -------------------------------------------------------------------------- */
/* Queries                                                                    */
/* -------------------------------------------------------------------------- */

/** Index entries by id for O(1) lookup. */
export function indexById(
  entries: readonly AnyAssetEntry[]
): ReadonlyMap<string, AnyAssetEntry> {
  const map = new Map<string, AnyAssetEntry>();
  for (const entry of entries) map.set(entry.id, entry);
  return map;
}

/** Bytes of the output that would be fetched for `entry` at `tier`. */
export function outputBytes(entry: AnyAssetEntry, tier: QualityTier): number {
  return entry.outputs.find((output) => output.tier === tier)?.bytes ?? 0;
}

/**
 * Texture ids a material binds, in the order they must be resident before the
 * material can be built.
 */
export function materialTextureKeys(entry: AnyAssetEntry): readonly string[] {
  if (entry.kind !== 'material') return [];
  return Object.values(entry.textureKeys).filter((key): key is string => typeof key === 'string');
}
