/**
 * CHARACTER BAKER — roster in, shippable character assets out
 *
 *   npx tsx tools/build-characters.ts [--only saitama,genos] [--size 1024]
 *                                     [--no-ao] [--no-vat] [--no-glb]
 *
 * For every entry in `@/characters/roster` this writes, into
 * `public/assets/chr/<name>/` (gitignored, re-derivable):
 *
 *   albedo.<tier>.png   base colour; ALPHA is the crowd tint mask
 *   orm.<tier>.png      AO (R) / roughness (G) / metalness (B)
 *   normal.<tier>.png   tangent-space normal
 *   emissive.<tier>.png only for characters that actually glow
 *   face.<tier>.png     four expression tiles, stacked, straight alpha
 *   <name>.glb          LOD0 + LOD1, skinned, textures embedded
 *   vat.bin / vat.json  animation texture for the instanced crowd
 *
 * and, into the committed `tools/manifest/characters.json`, a DETERMINISTIC
 * declaration of what those files are: ids, roles, colour spaces, tiers,
 * triangle counts, threat tiers, and the licence of every CC0 texture the bake
 * consumed. No timestamps and no build hashes go in the committed file — it
 * describes the roster, not one particular run, so re-running the baker
 * produces no diff unless the roster actually changed.
 *
 * ── WHERE THE PIXELS COME FROM ────────────────────────────────────────────
 * Two sources, and the split is deliberate:
 *
 *   CC0 PHOTOGRAPHY  the Poly Haven maps the texture pipeline already fetched.
 *                    Metal, vents, joints and painted shells sample the real
 *                    4k albedo/normal/ARM. Genos' forearms are literally
 *                    `metal_plate` — its ARM map drives roughness per texel.
 *   SYNTHESIS        weave, twill, canvas, leather grain, pores, hair strands,
 *                    scales and carapace cells are generated. The CC0 library
 *                    is a CITY library and contains no cloth; tiling brick onto
 *                    a jumpsuit would look worse than no map at all.
 *
 * Faces are rasterised from SVG through `sharp`, twice: once at the atlas patch
 * size so the GLB is self-contained, and once at full tile resolution for the
 * expression strip the material samples at runtime.
 *
 * NOTHING here downloads a character asset. Every mesh is generated by
 * `@/characters/mesh`; every texture is either synthesised or CC0 with a
 * recorded author.
 */

import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import * as THREE from 'three';
import sharp from 'sharp';
import { Document, NodeIO, type Accessor } from '@gltf-transform/core';
import { MeshBVH } from 'three-mesh-bvh';
import type { HumanoidBuild, LodLevel } from '@/characters/mesh';
import { buildHumanoid } from '@/characters/mesh';
import {
  EXPRESSIONS,
  bakeCharacterAtlas,
  buildClassifier,
  characterDir,
  entryClasses,
  entryGlows,
  faceRegion,
  faceSvg,
  listRoster,
  mapAssetId,
  mapFileName,
  materialAssetId,
  materialSpecFor,
  measureHead,
  prepareRosterGeometry,
  resolveSurfaces,
  usedDetailMaterialIds,
  type AtlasPlan,
  type DetailTile,
  type FacePatch,
  type OcclusionSampler,
  type RosterEntry,
} from '@/characters/roster';
import { createRng } from '@/util';

/* -------------------------------------------------------------------------- */
/* Paths and constants                                                        */
/* -------------------------------------------------------------------------- */

const REPO_ROOT = path.resolve(import.meta.dirname, '..');
const SOURCE_DIR = path.join(REPO_ROOT, 'assets', 'source');
const OUT_ROOT = path.join(REPO_ROOT, 'public', 'assets');
const MANIFEST_FILE = path.join(REPO_ROOT, 'tools', 'manifest', 'characters.json');
const TEXTURE_MANIFEST = path.join(REPO_ROOT, 'tools', 'manifest', 'textures.json');

/** Atlas edge per quality tier. `ultra` reuses the `high` bake. */
const TIER_SIZE: Readonly<Record<string, number>> = { mobile: 512, high: 1024, ultra: 1024 };
const TIERS = ['mobile', 'high'] as const;
type Tier = (typeof TIERS)[number];

/** Edge of the decoded CC0 detail tiles fed to the baker. */
const DETAIL_TILE_SIZE = 512;

/** Occlusion grid; AO is low-frequency, so it is baked coarse and upsampled. */
const AO_GRID = 256;
const AO_RAYS = 14;
const AO_RADIUS = 0.34;

/** LODs baked into the GLB. LOD2 is the crowd tier and ships via the VAT. */
const GLB_LODS: readonly LodLevel[] = [0, 1];

/** Our own attribution block. Every mesh and every synthesised map is ours. */
const PROJECT_ATTRIBUTION = {
  license: 'MIT',
  author: 'Saitama project (procedural)',
  sourceUrl: 'https://github.com/saitama-one-punch',
  modifications: 'Generated procedurally by tools/build-characters.ts; no third-party character art.',
} as const;

/* -------------------------------------------------------------------------- */
/* CLI                                                                        */
/* -------------------------------------------------------------------------- */

interface Options {
  readonly only: readonly string[];
  readonly size: number;
  readonly ao: boolean;
  readonly vat: boolean;
  readonly glb: boolean;
  readonly manifest: boolean;
}

function parseArgs(argv: readonly string[]): Options {
  let only: string[] = [];
  let size = TIER_SIZE.high!;
  let ao = true;
  let vat = true;
  let glb = true;
  let manifest = true;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]!;
    if (arg === '--only') only = (argv[++i] ?? '').split(',').filter(Boolean);
    else if (arg === '--size') size = Number(argv[++i] ?? size);
    else if (arg === '--no-ao') ao = false;
    else if (arg === '--no-vat') vat = false;
    else if (arg === '--no-glb') glb = false;
    else if (arg === '--no-manifest') manifest = false;
  }
  return { only, size, ao, vat, glb, manifest };
}

function matches(entry: RosterEntry, only: readonly string[]): boolean {
  if (only.length === 0) return true;
  return only.some((filter) => entry.id === filter || entry.id.endsWith(`.${filter}`));
}

/* -------------------------------------------------------------------------- */
/* CC0 detail tiles                                                           */
/* -------------------------------------------------------------------------- */

interface SourceFile {
  readonly role: string;
  readonly path: string;
}

interface TextureEntry {
  readonly id: string;
  readonly name: string;
  readonly attribution: {
    readonly license: string;
    readonly author: string;
    readonly sourceUrl: string;
    readonly attributionUrl?: string;
    readonly year?: number;
  };
  readonly files: readonly SourceFile[];
}

let textureEntries: Map<string, TextureEntry> | undefined;

async function loadTextureManifest(): Promise<Map<string, TextureEntry>> {
  if (textureEntries !== undefined) return textureEntries;
  const raw = JSON.parse(await readFile(TEXTURE_MANIFEST, 'utf8')) as {
    entries: readonly TextureEntry[];
  };
  textureEntries = new Map(raw.entries.map((entry) => [entry.id, entry]));
  return textureEntries;
}

const tileCache = new Map<string, DetailTile | undefined>();

/**
 * Decode one CC0 material into a small tiling detail source.
 *
 * The 4k source is 10-15 MB of JPEG; the bake needs a few hundred texels of
 * grain, not a photograph. Downsampling to 512 up front makes every subsequent
 * lookup a cache hit in L2 and makes the whole bake CPU-bound on the rasteriser
 * rather than on image decode.
 */
async function loadDetailTile(id: string): Promise<DetailTile | undefined> {
  const cached = tileCache.get(id);
  if (cached !== undefined || tileCache.has(id)) return cached;

  const manifest = await loadTextureManifest();
  const entry = manifest.get(id);
  if (entry === undefined) {
    console.warn(`  ! detail material "${id}" is not in the texture manifest — skipping`);
    tileCache.set(id, undefined);
    return undefined;
  }

  const pick = (role: string): string | undefined =>
    entry.files.find((file) => file.role === role)?.path;

  const albedoPath = pick('albedo');
  const normalPath = pick('normal');
  const armPath = pick('orm') ?? pick('arm');
  if (albedoPath === undefined || normalPath === undefined || armPath === undefined) {
    console.warn(`  ! detail material "${id}" is missing a map — skipping`);
    tileCache.set(id, undefined);
    return undefined;
  }

  const read = async (relative: string): Promise<Uint8Array> => {
    const buffer = await sharp(path.join(SOURCE_DIR, relative))
      .resize(DETAIL_TILE_SIZE, DETAIL_TILE_SIZE, { fit: 'fill', kernel: 'lanczos3' })
      .removeAlpha()
      .raw()
      .toBuffer();
    return new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength);
  };

  let albedo: Uint8Array;
  let normal: Uint8Array;
  let arm: Uint8Array;
  try {
    [albedo, normal, arm] = await Promise.all([read(albedoPath), read(normalPath), read(armPath)]);
  } catch (error) {
    console.warn(`  ! detail material "${id}" failed to decode: ${(error as Error).message}`);
    tileCache.set(id, undefined);
    return undefined;
  }

  let luma = 0;
  let rough = 0;
  const texels = DETAIL_TILE_SIZE * DETAIL_TILE_SIZE;
  for (let i = 0; i < texels; i++) {
    const o = i * 3;
    const r = srgbToLinear(albedo[o]! / 255);
    const g = srgbToLinear(albedo[o + 1]! / 255);
    const b = srgbToLinear(albedo[o + 2]! / 255);
    luma += 0.2126 * r + 0.7152 * g + 0.0722 * b;
    rough += arm[o + 1]! / 255;
  }

  const tile: DetailTile = {
    id,
    size: DETAIL_TILE_SIZE,
    albedo,
    normal,
    arm,
    meanLuma: Math.max(luma / texels, 1e-3),
    meanRough: Math.max(rough / texels, 1e-3),
  };
  tileCache.set(id, tile);
  return tile;
}

function srgbToLinear(value: number): number {
  return value <= 0.04045 ? value / 12.92 : Math.pow((value + 0.055) / 1.055, 2.4);
}

/* -------------------------------------------------------------------------- */
/* Faces                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Rasterise an SVG into the atlas' orientation.
 *
 * `.flip()` is the whole reason this helper exists: face art is authored the
 * way a person draws a face — brow at the top — while the atlas stores row 0
 * at v = 0, which puts the brow at the BOTTOM. Flipping once here keeps the
 * authoring readable and every consumer downstream flip-free.
 */
async function rasteriseFace(svg: string, width: number, height: number): Promise<FacePatch> {
  const { data } = await sharp(Buffer.from(svg), { density: 96 })
    .resize(width, height, { fit: 'fill' })
    .flip()
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  return {
    rgba: new Uint8Array(data.buffer, data.byteOffset, data.byteLength),
    width,
    height,
  };
}

/* -------------------------------------------------------------------------- */
/* Occlusion                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * Ray-traced ambient occlusion over the character itself.
 *
 * Fourteen cosine-weighted rays per sample, capped at 34 cm, so the signal is
 * CONTACT occlusion — the shadow under a chin, inside an armpit, between the
 * cape and the back — not a global bent-normal. That is the part a stylised
 * character actually needs: it grounds the costume against the body, which is
 * the single thing flat vertex colour cannot do.
 */
function makeOcclusion(build: HumanoidBuild): OcclusionSampler {
  const geometry = build.geometry.clone();
  geometry.deleteAttribute('color');
  geometry.deleteAttribute('skinIndex');
  geometry.deleteAttribute('skinWeight');
  const bvh = new MeshBVH(geometry);

  const rng = createRng(0x5a17a).derive('ao');
  const directions: [number, number, number][] = [];
  for (let i = 0; i < AO_RAYS; i++) {
    // Cosine-weighted hemisphere around +Z, stratified by a golden-angle spiral
    // so fourteen rays cover the dome evenly instead of clumping.
    const u = (i + 0.5) / AO_RAYS;
    const r = Math.sqrt(u);
    const phi = i * 2.399963 + rng.range(0, 0.4);
    directions.push([r * Math.cos(phi), r * Math.sin(phi), Math.sqrt(Math.max(0, 1 - u))]);
  }

  const ray = new THREE.Ray();
  const tangent = new THREE.Vector3();
  const bitangent = new THREE.Vector3();
  const normal = new THREE.Vector3();
  const helper = new THREE.Vector3();

  return (positions, normals, count) => {
    const out = new Float32Array(count);
    for (let i = 0; i < count; i++) {
      const o = i * 3;
      normal.set(normals[o]!, normals[o + 1]!, normals[o + 2]!);
      if (normal.lengthSq() < 0.5) {
        out[i] = 1;
        continue;
      }
      helper.set(0, 0, 1);
      if (Math.abs(normal.z) > 0.9) helper.set(1, 0, 0);
      tangent.crossVectors(helper, normal).normalize();
      bitangent.crossVectors(normal, tangent);

      let open = 0;
      for (const [dx, dy, dz] of directions) {
        ray.origin
          .set(positions[o]!, positions[o + 1]!, positions[o + 2]!)
          .addScaledVector(normal, 1.5e-3);
        ray.direction
          .set(0, 0, 0)
          .addScaledVector(tangent, dx)
          .addScaledVector(bitangent, dy)
          .addScaledVector(normal, dz)
          .normalize();
        const hit = bvh.raycastFirst(ray, THREE.DoubleSide, 0, AO_RADIUS);
        if (hit === null) open += 1;
        else open += Math.min(1, hit.distance / AO_RADIUS) * 0.55;
      }
      out[i] = open / AO_RAYS;
    }
    return out;
  };
}

/* -------------------------------------------------------------------------- */
/* PNG writing                                                                */
/* -------------------------------------------------------------------------- */

async function writePng(
  file: string,
  data: Uint8Array,
  size: number,
  channels: 3 | 4,
  resizeTo?: number
): Promise<number> {
  let image = sharp(Buffer.from(data.buffer, data.byteOffset, data.byteLength), {
    raw: { width: size, height: size, channels },
  });
  if (resizeTo !== undefined && resizeTo !== size) {
    image = image.resize(resizeTo, resizeTo, { kernel: 'lanczos3', fit: 'fill' });
  }
  const png = await image.png({ compressionLevel: 9, effort: 8 }).toBuffer();
  await writeFile(file, png);
  return png.byteLength;
}

function sha256(data: Uint8Array | Buffer): string {
  return createHash('sha256').update(data).digest('hex');
}

/* -------------------------------------------------------------------------- */
/* GLB                                                                        */
/* -------------------------------------------------------------------------- */

interface GlbInput {
  readonly entry: RosterEntry;
  readonly builds: readonly { lod: LodLevel; build: HumanoidBuild }[];
  readonly albedo: Buffer;
  readonly orm: Buffer;
  readonly normal: Buffer;
  readonly emissive?: Buffer;
}

/**
 * Write one character as a self-contained, skinned GLB.
 *
 * The ORM packing is not a convention we invented — it is exactly glTF's:
 * `occlusionTexture` reads R, `metallicRoughnessTexture` reads G and B. So one
 * embedded image serves both slots and any glTF viewer shows the character
 * correctly without knowing anything about this project.
 */
async function writeGlb(input: GlbInput, file: string): Promise<number> {
  const doc = new Document();
  doc.createBuffer();
  const buffer = doc.getRoot().listBuffers()[0]!;
  const scene = doc.createScene(input.entry.name);

  const texture = (name: string, data: Buffer): ReturnType<Document['createTexture']> =>
    doc
      .createTexture(name)
      .setImage(new Uint8Array(data.buffer, data.byteOffset, data.byteLength))
      .setMimeType('image/png');

  // ONE ORM texture object serves both slots. Creating two would embed the
  // same PNG twice — glTF's occlusion and metallic-roughness textures are
  // allowed to share an image precisely because R and GB never collide.
  const ormTexture = texture('orm', input.orm);
  const material = doc
    .createMaterial(input.entry.name)
    .setBaseColorFactor([1, 1, 1, 1])
    .setBaseColorTexture(texture('albedo', input.albedo))
    .setMetallicFactor(1)
    .setRoughnessFactor(1)
    .setMetallicRoughnessTexture(ormTexture)
    .setOcclusionTexture(ormTexture)
    .setNormalTexture(texture('normal', input.normal))
    .setDoubleSided(false);
  if (input.emissive !== undefined) {
    material.setEmissiveFactor([1, 1, 1]).setEmissiveTexture(texture('emissive', input.emissive));
  }

  // One skeleton serves every LOD: the bones are identical, only the surface
  // changes. Built from LOD0's rig.
  const primary = input.builds[0]!.build;
  const bones = primary.rig.bones;
  const nodes = bones.map((bone) =>
    doc
      .createNode(bone.name)
      .setTranslation([bone.position.x, bone.position.y, bone.position.z])
      .setRotation([bone.quaternion.x, bone.quaternion.y, bone.quaternion.z, bone.quaternion.w])
      .setScale([bone.scale.x, bone.scale.y, bone.scale.z])
  );
  for (let i = 0; i < bones.length; i++) {
    const parent = bones[i]!.parent;
    const parentIndex = parent === null ? -1 : bones.indexOf(parent as THREE.Bone);
    if (parentIndex >= 0) nodes[parentIndex]!.addChild(nodes[i]!);
  }
  const rootIndex = bones.findIndex((bone) => !bones.includes(bone.parent as THREE.Bone));
  scene.addChild(nodes[Math.max(0, rootIndex)]!);

  const inverses = new Float32Array(bones.length * 16);
  primary.rig.skeleton.boneInverses.forEach((matrix, i) => {
    inverses.set(matrix.elements, i * 16);
  });
  const ibm = doc.createAccessor('ibm').setType('MAT4').setArray(inverses).setBuffer(buffer);

  const skin = doc
    .createSkin('rig')
    .setInverseBindMatrices(ibm)
    .setSkeleton(nodes[Math.max(0, rootIndex)]!);
  for (const node of nodes) skin.addJoint(node);

  for (const { lod, build } of input.builds) {
    const geometry = build.geometry;
    const accessor = (
      name: string,
      type: 'VEC2' | 'VEC3' | 'VEC4' | 'SCALAR',
      array: Float32Array | Uint16Array | Uint32Array
    ): Accessor => doc.createAccessor(name).setType(type).setArray(array).setBuffer(buffer);

    const position = geometry.getAttribute('position');
    const normal = geometry.getAttribute('normal');
    const uv = geometry.getAttribute('uv');
    const skinIndex = geometry.getAttribute('skinIndex');
    const skinWeight = geometry.getAttribute('skinWeight');
    const index = geometry.getIndex()!;

    const primitive = doc
      .createPrimitive()
      .setAttribute('POSITION', accessor('P', 'VEC3', new Float32Array(position.array)))
      .setAttribute('NORMAL', accessor('N', 'VEC3', new Float32Array(normal.array)))
      .setAttribute('TEXCOORD_0', accessor('UV', 'VEC2', new Float32Array(uv.array)))
      .setAttribute('JOINTS_0', accessor('J', 'VEC4', new Uint16Array(skinIndex.array)))
      .setAttribute('WEIGHTS_0', accessor('W', 'VEC4', new Float32Array(skinWeight.array)))
      .setIndices(accessor('I', 'SCALAR', new Uint32Array(index.array)))
      .setMaterial(material);

    const mesh = doc.createMesh(`${input.entry.name} LOD${lod}`).addPrimitive(primitive);
    const node = doc.createNode(`${input.entry.id}_LOD${lod}`).setMesh(mesh).setSkin(skin);
    scene.addChild(node);
  }

  const io = new NodeIO();
  const glb = await io.writeBinary(doc);
  await writeFile(file, glb);
  return glb.byteLength;
}

/* -------------------------------------------------------------------------- */
/* VAT                                                                        */
/* -------------------------------------------------------------------------- */

interface VatResult {
  readonly bytes: number;
  readonly width: number;
  readonly height: number;
  readonly clips: number;
}

/**
 * Bake the animation texture the instanced crowd samples.
 *
 * One bake serves every character on the shared skeleton, but each character's
 * bone LENGTHS differ, so the palette is per-character. The payload is raw
 * half-float RGBA — a `.bin` rather than a PNG, because a PNG cannot carry
 * half floats and the runtime wants a `DataTexture` anyway.
 */
async function writeVat(build: HumanoidBuild, dir: string): Promise<VatResult | undefined> {
  const anim = await import('@/characters/anim');
  const rig = anim.resolveRig({
    skeleton: build.rig.skeleton,
    profile: build.profile,
    getBone: (name) => build.rig.bones[build.rig.index[name]],
  });
  const bake = anim.bakeVat(rig, anim.allClips(), { frames: 32, halfFloat: true });
  const data = bake.data as Uint16Array;
  const bytes = Buffer.from(data.buffer, data.byteOffset, data.byteLength);
  await writeFile(path.join(dir, 'vat.bin'), bytes);
  await writeFile(
    path.join(dir, 'vat.json'),
    `${JSON.stringify(
      {
        width: bake.width,
        height: bake.height,
        boneCount: bake.boneCount,
        halfFloat: bake.halfFloat,
        format: 'RGBA16F',
        frames: 32,
        clips: bake.clips,
      },
      null,
      2
    )}\n`
  );
  const result: VatResult = {
    bytes: bytes.byteLength,
    width: bake.width,
    height: bake.height,
    clips: bake.clips.length,
  };
  bake.dispose();
  return result;
}

/* -------------------------------------------------------------------------- */
/* One character                                                              */
/* -------------------------------------------------------------------------- */

interface BuiltFile {
  readonly key: string;
  readonly role: string;
  readonly tier?: Tier;
  readonly file: string;
  readonly bytes: number;
  readonly sha256: string;
  readonly width?: number;
  readonly height?: number;
}

interface CharacterReport {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
  readonly threat?: string;
  readonly height: number;
  readonly triangles: Record<string, number>;
  readonly classes: readonly string[];
  readonly cc0: readonly string[];
  readonly coverage: number;
  readonly atlasSize: number;
  readonly faceTile: [number, number];
  readonly files: readonly BuiltFile[];
  readonly gpuBytes: Record<Tier, number>;
  readonly vat?: VatResult;
  readonly remapped: readonly string[];
  readonly seconds: number;
}

async function buildCharacter(entry: RosterEntry, options: Options): Promise<CharacterReport> {
  const started = Date.now();
  const dir = path.join(OUT_ROOT, characterDir(entry));
  await mkdir(dir, { recursive: true });

  const styles = resolveSurfaces(entry.surfaces);
  const classifier = buildClassifier(entry.colors);

  // --- geometry, one plan shared by every LOD ------------------------------
  const builds: { lod: LodLevel; build: HumanoidBuild }[] = [];
  let plan: AtlasPlan | undefined;
  let remapped: readonly string[] = [];
  for (const lod of [0, 1, 2] as LodLevel[]) {
    const build = buildHumanoid(entry.recipe.profile, { ...entry.recipe.options, lod });
    const prepared = prepareRosterGeometry(build, plan);
    plan = prepared.plan;
    if (lod === 0) remapped = prepared.remapped;
    builds.push({ lod, build });
  }
  const primary = builds[0]!.build;

  // --- face ---------------------------------------------------------------
  const head = measureHead(primary);
  const region = faceRegion(entry.face, head);
  const rest = entry.restExpression ?? 'neutral';

  const atlasFaceWidth = Math.max(
    8,
    Math.round((region.atlas.u1 - region.atlas.u0) * options.size)
  );
  const atlasFaceHeight = Math.max(
    8,
    Math.round((region.atlas.v1 - region.atlas.v0) * options.size)
  );

  const face = await rasteriseFace(
    faceSvg(entry.face, rest, region, 'albedo'),
    atlasFaceWidth,
    atlasFaceHeight
  );
  const faceOrm = await rasteriseFace(
    faceSvg(entry.face, rest, region, 'orm'),
    atlasFaceWidth,
    atlasFaceHeight
  );
  const faceEmissive = entryGlows(entry)
    ? await rasteriseFace(
        faceSvg(entry.face, rest, region, 'emissive'),
        atlasFaceWidth,
        atlasFaceHeight
      )
    : undefined;

  // --- detail tiles -------------------------------------------------------
  const classes = entryClasses(entry);
  const cc0 = usedDetailMaterialIds(styles, classes);
  const tiles = new Map<string, DetailTile>();
  for (const id of cc0) {
    const tile = await loadDetailTile(id);
    if (tile !== undefined) tiles.set(id, tile);
  }

  // --- atlas --------------------------------------------------------------
  const maps = bakeCharacterAtlas(primary, styles, classifier, {
    size: options.size,
    seed: entry.seed,
    tiles,
    face,
    faceOrm,
    faceEmissive,
    faceRect: region.atlas,
    occlusion: options.ao ? makeOcclusion(primary) : undefined,
    occlusionSize: AO_GRID,
    neutralize: entry.crowd === true,
  });

  // --- write maps ---------------------------------------------------------
  const files: BuiltFile[] = [];
  const gpuBytes = { mobile: 0, high: 0 } as Record<Tier, number>;

  for (const tier of TIERS) {
    const size = Math.min(TIER_SIZE[tier]!, maps.size);
    const write = async (
      role: 'albedo' | 'orm' | 'normal' | 'emissive',
      data: Uint8Array,
      channels: 3 | 4
    ): Promise<void> => {
      const name = mapFileName(role, tier);
      const bytes = await writePng(path.join(dir, name), data, maps.size, channels, size);
      files.push({
        key: mapAssetId(entry, role),
        role,
        tier,
        file: `${characterDir(entry)}/${name}`,
        bytes,
        sha256: sha256(await readFile(path.join(dir, name))),
        width: size,
        height: size,
      });
      // Uncompressed GPU footprint including the mip chain.
      gpuBytes[tier] += Math.round(size * size * channels * 1.34);
    };
    await write('albedo', maps.albedo, 4);
    await write('orm', maps.orm, 3);
    await write('normal', maps.normal, 3);
    if (maps.emissive !== undefined) await write('emissive', maps.emissive, 3);
  }

  // --- expression strip ---------------------------------------------------
  // Four tiles stacked bottom-up in v, so tile 0 is `EXPRESSIONS[0]` and the
  // shader selects with one uniform. Tiered like every other map: at 224 px a
  // face is still sharper than its footprint in the atlas, and the strip would
  // otherwise dominate the mobile budget.
  const tiles4: Buffer[] = [];
  for (const expression of EXPRESSIONS) {
    const patch = await rasteriseFace(
      faceSvg(entry.face, expression, region, 'albedo'),
      region.tileWidth,
      region.tileHeight
    );
    tiles4.push(Buffer.from(patch.rgba.buffer, patch.rgba.byteOffset, patch.rgba.byteLength));
  }
  const stripHeight = region.tileHeight * EXPRESSIONS.length;
  const strip = Buffer.concat(tiles4);
  for (const tier of TIERS) {
    const width = tier === 'high' ? region.tileWidth : Math.round(region.tileWidth / 2);
    const height = tier === 'high' ? stripHeight : Math.round(stripHeight / 2);
    let image = sharp(strip, { raw: { width: region.tileWidth, height: stripHeight, channels: 4 } });
    if (tier !== 'high') image = image.resize(width, height, { kernel: 'lanczos3', fit: 'fill' });
    const stripPng = await image.png({ compressionLevel: 9, effort: 8 }).toBuffer();
    const name = `face.${tier}.png`;
    await writeFile(path.join(dir, name), stripPng);
    files.push({
      key: mapAssetId(entry, 'face'),
      role: 'face',
      tier,
      file: `${characterDir(entry)}/${name}`,
      bytes: stripPng.byteLength,
      sha256: sha256(stripPng),
      width,
      height,
    });
    gpuBytes[tier] += Math.round(width * height * 4 * 1.34);
  }

  // --- GLB ----------------------------------------------------------------
  if (options.glb) {
    const glbFile = path.join(dir, 'model.glb');
    const bytes = await writeGlb(
      {
        entry,
        builds: builds.filter(({ lod }) => GLB_LODS.includes(lod)),
        albedo: await readFile(path.join(dir, mapFileName('albedo', 'high'))),
        orm: await readFile(path.join(dir, mapFileName('orm', 'high'))),
        normal: await readFile(path.join(dir, mapFileName('normal', 'high'))),
        emissive:
          maps.emissive === undefined
            ? undefined
            : await readFile(path.join(dir, mapFileName('emissive', 'high'))),
      },
      glbFile
    );
    files.push({
      key: entry.id,
      role: 'model',
      file: `${characterDir(entry)}/model.glb`,
      bytes,
      sha256: sha256(await readFile(glbFile)),
    });
  }

  // --- VAT ----------------------------------------------------------------
  let vat: VatResult | undefined;
  if (options.vat) {
    try {
      vat = await writeVat(primary, dir);
      if (vat !== undefined) {
        files.push({
          key: `${entry.id}.vat`,
          role: 'vat',
          file: `${characterDir(entry)}/vat.bin`,
          bytes: vat.bytes,
          sha256: sha256(await readFile(path.join(dir, 'vat.bin'))),
          width: vat.width,
          height: vat.height,
        });
      }
    } catch (error) {
      console.warn(`  ! VAT bake failed for ${entry.id}: ${(error as Error).message}`);
    }
  }

  const triangles: Record<string, number> = {};
  for (const { lod, build } of builds) triangles[`lod${lod}`] = build.stats.triangles;
  for (const { build } of builds) build.geometry.dispose();

  return {
    id: entry.id,
    name: entry.name,
    kind: entry.kind,
    threat: entry.threat,
    height: Number(primary.stats.height.toFixed(3)),
    triangles,
    classes,
    cc0,
    coverage: Number(maps.coverage.toFixed(4)),
    atlasSize: maps.size,
    faceTile: [region.tileWidth, region.tileHeight],
    files,
    gpuBytes,
    vat,
    remapped,
    seconds: Number(((Date.now() - started) / 1000).toFixed(2)),
  };
}

/* -------------------------------------------------------------------------- */
/* Manifests                                                                  */
/* -------------------------------------------------------------------------- */

interface ManifestAttribution {
  readonly license: string;
  readonly author: string;
  readonly sourceUrl: string;
  readonly attributionUrl?: string;
  readonly year?: number;
}

async function cc0Attribution(ids: readonly string[]): Promise<Record<string, ManifestAttribution>> {
  const manifest = await loadTextureManifest();
  const out: Record<string, ManifestAttribution> = {};
  for (const id of ids) {
    const entry = manifest.get(id);
    if (entry !== undefined) out[id] = entry.attribution;
  }
  return out;
}

/**
 * The committed manifest.
 *
 * Deterministic by construction: no timestamps, no build hashes, keys in a
 * fixed order. Re-running the baker on an unchanged roster produces no diff,
 * which is what makes this file reviewable.
 */
async function writeSourceManifest(reports: readonly CharacterReport[]): Promise<void> {
  const roster = new Map(listRoster().map((entry) => [entry.id, entry]));
  const allCc0 = [...new Set(reports.flatMap((report) => report.cc0))].sort();
  const attribution = await cc0Attribution(allCc0);

  const entries = reports.map((report) => {
    const entry = roster.get(report.id)!;
    const spec = materialSpecFor(entry);
    const glows = entryGlows(entry);
    const roles = ['albedo', 'orm', 'normal', ...(glows ? ['emissive'] : [])];

    return {
      id: entry.id,
      kind: 'character',
      name: entry.name,
      role: entry.kind,
      threat: entry.threat,
      targetFormat: 'glb',
      skeleton: 'mixamo',
      height: report.height,
      triangles: report.triangles.lod0,
      attribution: PROJECT_ATTRIBUTION,
      sourceUrl: PROJECT_ATTRIBUTION.sourceUrl,
      generator: 'tools/build-characters.ts',
      directory: characterDir(entry),
      model: 'model.glb',
      lodLevels: GLB_LODS.map((lod) => ({
        level: lod,
        file: `${characterDir(entry)}/model.glb`,
        triangles: report.triangles[`lod${lod}`] ?? 0,
      })),
      crowdLod: { level: 2, triangles: report.triangles.lod2 ?? 0, delivery: 'vat' },
      materialKeys: [materialAssetId(entry)],
      material: { id: materialAssetId(entry), kind: 'material', spec },
      textures: roles.map((role) => ({
        id: mapAssetId(entry, role as 'albedo'),
        role: role === 'albedo' ? 'albedo' : role,
        colorSpace: role === 'albedo' || role === 'emissive' ? 'srgb' : 'linear',
        targetFormat: 'png',
        tileable: false,
        files: TIERS.map((tier) => ({
          tier,
          file: `${characterDir(entry)}/${mapFileName(role as 'albedo', tier)}`,
          size: Math.min(TIER_SIZE[tier]!, report.atlasSize),
        })),
      })),
      face: {
        id: mapAssetId(entry, 'face'),
        colorSpace: 'srgb',
        expressions: EXPRESSIONS,
        tile: report.faceTile,
        files: TIERS.map((tier) => ({
          tier,
          file: `${characterDir(entry)}/face.${tier}.png`,
        })),
      },
      vat: report.vat === undefined ? undefined : { file: `${characterDir(entry)}/vat.bin` },
      surfaceClasses: report.classes,
      cc0Textures: report.cc0,
    };
  });

  const manifest = {
    version: 1,
    kind: 'character',
    generator: 'tools/build-characters.ts',
    description:
      'Procedural character roster. Every mesh is generated by @/characters/mesh and every ' +
      'texture is either synthesised by @/characters/roster or a CC0 Poly Haven map listed in ' +
      'cc0Textures. No third-party character asset is used, downloaded or referenced anywhere ' +
      'in this roster.',
    atlas: {
      tiers: Object.fromEntries(TIERS.map((tier) => [tier, TIER_SIZE[tier]])),
      layout: 'row 0 = v 0; textures bind with flipY=false',
      packing: 'albedo RGB + crowd tint mask in A; ORM = AO(R)/roughness(G)/metalness(B)',
    },
    thirdPartyCharacterAssets: 0,
    cc0Attribution: attribution,
    entries,
  };

  await writeFile(MANIFEST_FILE, `${JSON.stringify(manifest, null, 2)}\n`);
}

/** The build report, written next to the binaries and gitignored. */
async function writeRuntimeIndex(reports: readonly CharacterReport[]): Promise<void> {
  const dir = path.join(OUT_ROOT, 'chr');
  await mkdir(dir, { recursive: true });
  await writeFile(
    path.join(dir, 'characters.runtime.json'),
    `${JSON.stringify({ generatedRoot: 'chr', characters: reports }, null, 2)}\n`
  );
}

/* -------------------------------------------------------------------------- */
/* Main                                                                       */
/* -------------------------------------------------------------------------- */

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  const roster = listRoster().filter((entry) => matches(entry, options.only));
  if (roster.length === 0) {
    console.error('no roster entries matched');
    process.exit(1);
  }

  console.log(
    `characters · ${roster.length} entries · atlas ${options.size} · ` +
      `ao=${options.ao} glb=${options.glb} vat=${options.vat}`
  );

  const reports: CharacterReport[] = [];
  for (const entry of roster) {
    process.stdout.write(`  ${entry.id.padEnd(20)} `);
    const report = await buildCharacter(entry, options);
    reports.push(report);
    const mb = (report.gpuBytes.high / (1024 * 1024)).toFixed(1);
    console.log(
      `${report.triangles.lod0} tris · coverage ${(report.coverage * 100).toFixed(1)}% · ` +
        `${mb} MB GPU · ${report.seconds}s`
    );
  }

  await writeRuntimeIndex(reports);
  if (options.manifest && options.only.length === 0) await writeSourceManifest(reports);

  const totalHigh = reports.reduce((sum, report) => sum + report.gpuBytes.high, 0);
  const totalMobile = reports.reduce((sum, report) => sum + report.gpuBytes.mobile, 0);
  console.log(
    `\ndone · ${reports.length} characters · GPU high ${(totalHigh / 1048576).toFixed(1)} MB · ` +
      `mobile ${(totalMobile / 1048576).toFixed(1)} MB`
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
